import React from 'react';

const PrintView = ({ encounterMonsters, partyES, totalEV, difficulty, partyCount, onBack }) => {
    // Deduplicate monsters for statblock display
    const uniqueMonsters = Array.from(new Set(encounterMonsters.map(m => m.name)))
        .map(name => encounterMonsters.find(m => m.name === name));

    // Sort monsters by role/power for the tracker
    const sortedMonsters = [...encounterMonsters].sort((a, b) => a.name.localeCompare(b.name));

    return (
        <div className="min-h-screen bg-white text-black p-8 font-serif print:p-0">
            {/* No-Print Controls */}
            <div className="print:hidden mb-8 flex justify-between items-center bg-gray-100 p-4 rounded border border-gray-300">
                <div>
                    <h2 className="font-bold text-lg">Print Preview</h2>
                    <p className="text-sm text-gray-600">Use your browser's print function (Ctrl+P / Cmd+P).</p>
                </div>
                <button
                    onClick={onBack}
                    className="bg-gray-800 text-white px-4 py-2 rounded hover:bg-gray-700"
                >
                    Back to Builder
                </button>
            </div>

            {/* Header Info */}
            <div className="flex justify-between items-end border-b-2 border-black pb-2 mb-6">
                <div>
                    <h1 className="text-2xl font-bold uppercase tracking-tight">Encounter Plan</h1>
                    <div className="text-xs mt-1">
                        <span className="font-bold mr-2">Difficulty:</span> {difficulty.toUpperCase()}
                        <span className="mx-2">|</span>
                        <span className="font-bold mr-2">Total EV:</span> {totalEV}
                        <span className="mx-2">|</span>
                        <span className="font-bold mr-2">Party ES:</span> {partyES}
                    </div>
                </div>
                <div className="text-right text-[10px] text-gray-500">
                    Generated by Draw Steel Encounter Builder
                </div>
            </div>

            {/* Trackers Section */}
            <div className="grid grid-cols-12 gap-4 mb-6">
                {/* Initiative / Condition Tracker */}
                <div className="col-span-8">
                    <h3 className="font-bold text-sm border-b border-black mb-1">Initiative & Condition Tracker</h3>
                    <table className="w-full text-xs text-left border-collapse">
                        <thead>
                            <tr className="border-b border-gray-400">
                                <th className="py-1 w-8 text-center border-r border-gray-300">Init</th>
                                <th className="py-1 pl-2 w-1/3 border-r border-gray-300">Name</th>
                                <th className="py-1 px-2 w-12 text-center border-r border-gray-300">Max HP</th>
                                <th className="py-1 px-2 w-16 border-r border-gray-300">Cur HP</th>
                                <th className="py-1 pl-2">Conditions / Notes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {/* Rows for Monsters */}
                            {sortedMonsters.map((monster, i) => (
                                <tr key={monster.id} className="border-b border-gray-200">
                                    <td className="py-2 border-r border-gray-300"></td>
                                    <td className="py-2 pl-2 font-semibold border-r border-gray-300">{monster.name}</td>
                                    <td className="py-2 text-center border-r border-gray-300">{monster.stats.stamina}</td>
                                    <td className="py-2 border-r border-gray-300"></td>
                                    <td className="py-2"></td>
                                </tr>
                            ))}
                            {/* Dynamic rows for Heroes */}
                            {Array.from({ length: partyCount }).map((_, i) => (
                                <tr key={`hero-${i}`} className="border-b border-gray-200 bg-gray-50">
                                    <td className="py-3 border-r border-gray-300"></td>
                                    <td className="py-3 pl-2 text-gray-500 italic border-r border-gray-300"></td>
                                    <td className="py-3 border-r border-gray-300"></td>
                                    <td className="py-3 border-r border-gray-300"></td>
                                    <td className="py-3"></td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {/* Malice Tracker */}
                <div className="col-span-4">
                    <h3 className="font-bold text-sm border-b border-black mb-1">Malice Tracker</h3>
                    <table className="w-full text-xs border-collapse">
                        <thead>
                            <tr className="border-b border-gray-400">
                                <th className="py-1 text-left w-12">Round</th>
                                <th className="py-1 text-left pl-2">Malice Earned / Spent</th>
                            </tr>
                        </thead>
                        <tbody>
                            {[1, 2, 3, 4, 5, 6].map(round => (
                                <tr key={round} className="border-b border-gray-200">
                                    <td className="py-3 font-bold align-top">Rd {round}</td>
                                    <td className="py-3 border-l border-gray-300"></td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Statblocks Section */}
            <div>
                <h3 className="font-bold text-sm border-b border-black mb-2">Statblocks</h3>

                {/* CSS Columns Layout for better print flow */}
                <div className="columns-1 md:columns-2 gap-4 space-y-4">
                    {uniqueMonsters.map((monster) => {
                        // "Smart" Layout Logic:
                        // If a monster is a "Solo" or "Leader", or has many abilities, it's "Complex".
                        // Complex monsters span the full width (breaking the columns), and their abilities are split into 2 columns.
                        const isComplex = monster.role === 'Solo' || monster.role === 'Leader' || monster.abilities.length > 6;

                        return (
                            <div
                                key={monster.name}
                                className={`border border-black p-2 break-inside-avoid text-xs ${isComplex ? 'column-span-all w-full mb-4' : 'mb-4'}`}
                            >
                                {/* Header */}
                                <div className="flex justify-between items-baseline border-b border-black pb-0.5 mb-1">
                                    <h4 className="font-bold text-sm">{monster.name}</h4>
                                    <span className="font-semibold">Lvl {monster.level} {monster.role}</span>
                                </div>

                                {/* Stats Grid */}
                                <div className="grid grid-cols-5 gap-1 text-center mb-2 bg-gray-100 p-0.5 rounded">
                                    <div>
                                        <div className="font-bold text-[10px] uppercase">Size</div>
                                        <div>{monster.stats.size}</div>
                                    </div>
                                    <div>
                                        <div className="font-bold text-[10px] uppercase">Speed</div>
                                        <div>{monster.stats.speed}</div>
                                    </div>
                                    <div>
                                        <div className="font-bold text-[10px] uppercase">Stamina</div>
                                        <div>{monster.stats.stamina}</div>
                                    </div>
                                    <div>
                                        <div className="font-bold text-[10px] uppercase">Stability</div>
                                        <div>{monster.stats.stability}</div>
                                    </div>
                                    <div>
                                        <div className="font-bold text-[10px] uppercase">Free Strike</div>
                                        <div>{monster.stats.freeStrike}</div>
                                    </div>
                                </div>

                                {/* Abilities */}
                                <div className={isComplex ? 'columns-2 gap-4 space-y-2' : 'space-y-2'}>
                                    {monster.abilities.map((ability, i) => (
                                        <div key={i} className="break-inside-avoid mb-2">
                                            <div className="font-bold flex items-center gap-1">
                                                <span>{ability.icon}</span>
                                                <span>{ability.name}</span>
                                                {ability.type && <span className="text-[10px] font-normal text-gray-600 ml-1">[{ability.type}]</span>}
                                            </div>

                                            {/* Keywords/Distance/Target Line */}
                                            {(ability.keywords?.length > 0 || ability.distance || ability.target) && (
                                                <div className="text-[10px] text-gray-600 mb-0.5 italic">
                                                    {[
                                                        ability.keywords?.join(', '),
                                                        ability.distance && `Dist: ${ability.distance}`,
                                                        ability.target && `Tgt: ${ability.target}`
                                                    ].filter(Boolean).join(' • ')}
                                                </div>
                                            )}

                                            <div className="text-gray-900 whitespace-pre-wrap leading-tight">
                                                {/* Simple markdown stripping/formatting for print */}
                                                {ability.description?.split('\n').map((line, j) => (
                                                    <div key={j} className="mb-0.5">
                                                        {line.replace(/\*\*/g, '')}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
    );
};

export default PrintView;
